[package]
name = "async-ssh2"
version = "0.1.0"
authors = ["spebern sp33cht@googlemail.com"]
license = "MIT/Apache-2.0"
keywords = ["ssh", "async"]
readme = "README.md"
repository = "https://github.com/spebern/async-ssh2"
homepage = "https://github.com/spebern/async-ssh2"
documentation = "https://docs.rs/async-ssh2"
description = """Async wrapper over ssh2 ."""
edition = "2018"

[features]
vendored-openssl = ["ssh2/vendored-openssl"]

[dependencies]
#ssh2 = "0.6"
ssh2 = { git = "https://github.com/spebern/ssh2-rs" }
tokio = { version = "0.2.6", features = ["full"] }
mio = { version = "0.6.21" }
libc = "0.2"

[dev-dependencies]
tempfile = "3.1"
